### PR TITLE
Set max amount of money fields

### LINKED ISSUE #244: Limiteer max-invoerveld "to prevent: PG::NumericValueOutOfRange"
Sentry Issue: [ALPHA-TOMATO-PRODUCTION-1K](https://sentry.io/csvalpha/alpha-tomato-production/issues/891393074/?referrer=github_integration)

```
PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 8, scale 2 must round to an absolute value less than 10^6.

  app/controllers/credit_mutations_controller.rb:17:in `block in create'
    if @mutation.save
  app/controllers/credit_mutations_controller.rb:16:in `create'
    respond_to do |format|
...
(114 additional frame(s) were not displayed)

ActiveRecord::RangeError: PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 8, scale 2 must round to an absolute value less than 10^6.
: INSERT INTO "credit_mutations" ("description", "user_id", "activity_id", "amount", "created_at", "updated_at", "created_by_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"

ActiveRecord::RangeError: PG::NumericValueOutOfRange: ERROR:  numeric field overflow
DETAIL:  A field with precision 8, scale 2 must round to an absolute value less than 10^6.
: INSERT INTO "credit_mutations" ("description", "user_id", "activity_id", "amount", "created_at", "updated_at", "created_by_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
```

### PR DESCRIPTION
**Pull request by Matthijsy**
Fixes #244 
Make the fields `CreditMutation.amount` and `ProductPrice.price` capped by a max to prevent database overflows

### CODE REVIEW

File: spec/models/credit_mutation_spec.rb [hunk 1]
```diff
@@ -30,6 +30,12 @@
       it { expect(mutation).not_to be_valid }
     end
 
+    context 'when with too much amount' do
```
Comment (cmitz) [inline spec/models/credit_mutation_spec.rb]:
```suggestion
    context 'when with too high amount' do
```

File: spec/models/product_price_spec.rb [hunk 2]
```diff
@@ -12,6 +12,12 @@
       it { expect(product_price).not_to be_valid }
     end
 
+    context 'when with too much price' do
```
Comment (cmitz) [inline spec/models/product_price_spec.rb]:
```suggestion
    context 'when with too high price' do
```
